apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boss
  labels:
    name: payara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: payara
    spec:
      containers:
      - name: boss
        image: merorai/boss
        imagePullPolicy: Always
        ports:
        - name: boss
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: boss
  labels:
    name: payara
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
    nodePort: 30002
  selector:
    name: payara

