apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
  labels:
    name: payara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: payara
    spec:
      containers:
      - name: console
        image: merorai/console
        imagePullPolicy: Always
        ports:
        - name: console
          containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    name: payara
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8081
    nodePort: 30001
  selector:
    name: payara

