---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dogsbody
  labels:
    name: dogsbody
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dogsbody
    spec:
      containers:
      - name: dogsbody
        image: merorai/dogsbody
        ports:
        - name: dogsbody
          containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: dogsbody
  labels:
    name: dogsbody
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8082
    nodePort: 30003
  selector:
    name: dogsbody

