apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serf
  labels:
    name: payara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: payara
    spec:
      containers:
      - name: serf
        image: merorai/serf
        imagePullPolicy: Always
        ports:
        - name: serf
          containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: serf
  labels:
    name: payara
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8084
    nodePort: 30005
  selector:
    name: payara


